on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  watch:
    types: [started]

jobs:
  npm-install-recent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install @jcansdale-test/npm-load@1.0.1049
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  npm-install-older:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install @jcansdale-test/npm-load@1.0.949
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
